gamma1/os_pcl_merger_node:
  ros__parameters:
    topics: ["/gamma1/os_center/points","/gamma1/os_left/points","/gamma1/os_right/points" ]
    frames: ["gamma1/TMF", "gamma1/LF", "gamma1/RF"]
    child_frames: ["null", "null"]
    target_frame: "gamma1/TMF"
    pub_topic_name: "sensing/lidar/concatenated/pointcloud"
    merger_freq: 20.0

    # ------------------------------
    # CropBox Filter Parameters
    # ------------------------------

    # Lexus RX450h dimensions:
    # Length: ~4.7 meters (4700 mm)
    # Width: ~1.9 meters (1900 mm)
    # Height: ~1.7 meters (1700 mm)

    # assuming right-handed coordinate system (X: forward, Y: left, Z: up)
    crop_box:
      # minimum boundaries of the CropBox (meters)
      min_x: -2.35    # Points with X < "val" will be excluded. (half of the vehicle's length backward)
      min_y: -0.95    # Points with Y < "val" will be excluded. (half of the vehicle's width to the right)
      min_z: -0.85    # Points with Z < "val" will be excluded. (slightly below the ground to account for any mounting height)
      
      # maximum boundaries of the CropBox (meters)
      max_x: 2.35     # Points with X > "val" will be excluded. (half of the vehicle's length forward)
      max_y: 0.95     # Points with Y > "val" will be excluded. (half of the vehicle's width to the left)
      max_z: 0.85     # Points with Z > "val" will be excluded. (slightly above the vehicle to account for the roof and mounting height)
      
      negative: true  # Set to true to invert the CropBox filter, filtering points inside the defined box.
      
      apply: false     # Set to true to apply the filter (on / off switch)
